### ISSUE TITLE
ERROR: rake redmine:plugins:migrate RAILS_ENV=production

### ISSUE THREAD

**Issue by monstrfolk** [riccardonar/mega_calendar_gc_sync#1]
rake aborted!
LoadError: No such file to load -- calendar_event
/usr/share/redmine/plugins/mega_calendar_gc_sync/init.rb:10:in `block in <top (required)>'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by monstrfolk** [comment]
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: No such file to load -- calendar_event
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:360:in `require_or_load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:317:in `depend_on'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:233:in `require_dependency'
/usr/share/redmine/plugins/mega_calendar_gc_sync/init.rb:10:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `instance_exec'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:192:in `block in simple'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:240:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/lib/ruby/vendor_ruby/rake/task.rb:240:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:235:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:165:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:100:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:78:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in main
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by riccardonar** [comment]
Do you use this plugin with my fork of [Mega Calendar](https://github.com/riccardonar/mega_calendar)?

**Comment by Exellent1988** [comment]
mine is not working as well. I tryed with your mega_calender fork:
```
Migrating mega_calendar (Mega Calendar plugin)...
Migrating mega_calendar_gc_sync (Mega Calendar: Gc Sync plugin)...
rake aborted!
NameError: uninitialized constant CreateCalendarEvents
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:778:in `load_migration'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:773:in `migration'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1051:in `use_transaction?'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:958:in `block in migrate'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:453:in `migrate'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:467:in `block in migrate'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:466:in `each'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:466:in `migrate'
/home/admin/web/brilliantshit.com/public_html/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
NameError: uninitialized constant CreateCalendarEvents
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:778:in `load_migration'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:773:in `migration'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1051:in `use_transaction?'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:453:in `migrate'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:467:in `block in migrate'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:466:in `each'
/home/admin/web/brilliantshit.com/public_html/lib/redmine/plugin.rb:466:in `migrate'
/home/admin/web/brilliantshit.com/public_html/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/admin/web/brilliantshit.com/public_html/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

```

**Comment by Exellent1988** [comment]
**UPDATE**

**Comment by riccardonar** [comment]
Thanks @Exellent1988
